### ISSUE TITLE
[Bug] Mass Downloading Issues & Unnecessary API Requests

### ISSUE THREAD

**Issue by T-prog3** [Jettcodey/TikTok-Downloader#16]
**Describe the bug**
There is an issue with downloading files from text files and Username_combined_links.txt. The downloader collects all links but it does not download them all. It appears as if it jumps over links without notifying the user about any error,
So everytime i have less downloaded files than links in the text file.

It is possible to rerun the same text file multiple times and get a couple of more files each run and eventually get everything downloaded but this should not be necessary.

**To Reproduce**
1. Download with any Mass Download option.
2. Compare number of files with number of links.
3. Rerun text file to get some more files.

**Comment by Jettcodey** [comment]
Hey, could you tell me if you are using version 1.2.9 or the pre-release 1.3.1 version

**Comment by Jettcodey** [comment]
Hey @T-prog3, I found the cause of the problem and released [Version 1.3.0](https://github.com/Jettcodey/TikTok-Downloader/releases/tag/Release-1.3.0), which should fix this issue.

I’d appreciate hearing back from you to confirm if the issue is resolved in this version.

**Comment by T-prog3** [comment]
I used version 1.2.9 but this new verion 1.3.0 is worse and made it so no videos gets downloaded. It collects videos but when downloading starts it goes from 0% to 100% in 1 sec and complete the processes without any files downloaded.

**Comment by Jettcodey** [comment]
@T-prog3 Could you activate the Download/Json Logs in the Settings and upload them here or record a video of what you're doing, cause I'm not able to recreate this issue in my Side.

**Comment by T-prog3** [comment]
A)
I did enable Download/JSON but there is no output files at all. This is the exact steps:
1. Open Tiktok Downloader 1.3.0
4. Change Download option to "Mass Download by Username"
5. Enter "tfpunch" in "Download by Username" input.
6. Have both checkmarks unchecked.
7. Press Download
8. Browser opens
9. Solve captcha by rotating image.
10. Downloader collects links
11. Browser shutdown
12. Download starts
13. Goes from 0% to 100% in 1 sec
14. No downloads in output folder. Not even a folder with the username. But you get the tfpunch_combined_links.txt with all links in it.

B) 
Noticed more issues:
1. All Settings are being reset to default everytime i press the download button.
2. There are some visibility issues in settings (see image).
![bug](https://github.com/user-attachments/assets/291ce909-ebd6-4897-a562-8843f2eed370)

**Comment by Jettcodey** [comment]
Hey @T-prog3,

The visibility issue you're experiencing is most likely due to Windows scaling being set above 100% (or your desktop resolution being set below 1280x720), which the application doesn’t currently support.

As for the download issue, Version 1.3.0 isn’t installing correctly, and I need to modify the installer. That’s why I temporarily took down Release 1.3.0. I sincerely apologize for the inconvenience.

**Comment by Jettcodey** [comment]
Hey @T-prog3,

This time, I’ve fixed the Download issue and resolved the visibility problems (Windows upscaling/DPI not supported).

I’ve now re-released [Version 1.3.0](https://github.com/Jettcodey/TikTok-Downloader/releases/tag/Release-1.3.0), which should address these issues.

I’d appreciate hearing back from you to confirm if the issue is resolved in this version, and I apologize again for the inconvenience.

**Comment by T-prog3** [comment]
A) 
I can confirm that downloading all links works as it should now. And that it fixed the visibility issue but there's still an issue where settings does not save properly.

1. Open settings
2. Make any changes (checkmark or custom browser)
3. Save settings and start downloading.
4. When done, check settings to see that all changes have been reverted, or if you use a non-default browser then next download will use your default. 

B)
Noticed another issue when updating an already downloaded user to get all posts, where the downloader makes unnecessary requests and 5 sec cooldowns. 

You have a loop that goes
1. request link
2. if 429 then cooldown
3. check if file already exist.
4. download

But we already have the would be filename from the videoID part of the url + _Save.mp4 so we could do the already exist check first and skip request + cooldown if we already have the file. It may also be a good idea to use a database or a username_Index.txt file with already downloaded links so that users can move files without having them redownloaded if they update.

**Comment by Jettcodey** [comment]
I will look into it as soon as possible :)

**Comment by Jettcodey** [comment]
Issues are resolved now. Keep in mind that the 5-second cooldown is necessary to prevent IP bans from TikTok.
